### ISSUE TITLE
How to troubleshoot realtime preview after deploying

### ISSUE THREAD

**Issue by jmn** [SimeonGriggs/simeonGriggs#1]
Hi! Thanks for this, it's very nice!

I tried deploying this to Vercel, as two projects, and setting the environment variables and CORS configuration and productionUrl but for some reason the realtime support doesn't work in production. Was just wondering if you had any ideas on what it might be or how to troubleshoot further. Realtime preview updates properly when running locally.

**Comment by SimeonGriggs** [comment]
I'd say take a look over the full guide I wrote for how to get Remix + Sanity with preview working in Production

https://www.sanity.io/guides/remix-run-live-preview

It's most likely the environment variable on your hosting isn't loading correctly.
